
name: "auto-release"

on:
  push:
    branches:
      - final

jobs:
  prepare-artifacts:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          skill: 
            - change_led
            - eye_contact
            - listen_answers
            - listen_voices
            - senior_robot
            - sense_touch
            - speak_from_url
            - take_photo_to_position
            - volume_check
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: skills/${{ matrix.skill }}/
          dest: dist/${{ matrix.skill }}.zip
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.skill }}.zip
          path: dist/${{ matrix.skill }}.zip
  auto-release:
    name: "Auto Release"
    runs-on: ubuntu-latest
    needs: prepare-artifacts
    steps:
      - name: Get current date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"
        id: date
      - name: Echo current date
        run: echo "${{ steps.date.outputs.date }}"
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: skills-files/
      - uses: ncipollo/release-action@v1
        with:
          tag: v3-${{ steps.date.outputs.date }}
          artifacts: "skills-files/*.zip/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}