
name: "auto-release"

on:
  push:
    branches:
      - prototype2

jobs:
  prepare-artifacts:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          skill: 
            - listen_answers
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: skills/${{ matrix.skill }}/
          dest: dist/${{ matrix.skill }}.zip
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.skill }}.zip
          path: dist/${{ matrix.skill }}.zip
  auto-release:
    name: "Auto Release"
    runs-on: ubuntu-latest
    needs: prepare-artifacts
    steps:
      - name: set env
        run: echo "::set-env name=NOW::$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: listen_answers.zip
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.NOW }}
          artifacts: "skills/manifest.json,*.zip"
          bodyFile: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}