
name: "auto-release"

on:
  push:
    branches:
      - prototype2

jobs:
  prepare-artifacts:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          skill: 
            - listen_answers
            - listen_voices
            - speak_from_url
            - eye_contact
            - take_photo_to_position
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: skills/${{ matrix.skill }}/
          dest: dist/${{ matrix.skill }}.zip
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.skill }}.zip
          path: dist/${{ matrix.skill }}.zip
  auto-release:
    name: "Auto Release"
    runs-on: ubuntu-latest
    needs: prepare-artifacts
    steps:
      - name: Get current date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"
        id: date
      - name: Echo current date
        run: echo "${{ steps.date.outputs.date }}"
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: skills/
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.date.outputs.date }}
          artifacts: "skills/manifest.json,skills/*.zip/*.zip"
          bodyFile: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}