
name: "auto-release"

on:
  push:
    branches:
      - release-test

jobs:
  auto-release:
    name: "Auto Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: skills/listen_answers/
          dest: dist/listen_answers.zip
      - uses: actions/upload-artifact@v2
        with:
          name: listen_answers.zip
          path: listen_answers.zip
      - uses: ncipollo/release-action@v1
        with:
          prerelease: true
          tag: latest
          artifacts: "skills/manifest.json,dist/*"
          bodyFile: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}